-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHKWVwatpZfNKQo+7
lhVlo2b6GomwMztQrzmu3psiZLagCgYIKoZIzj0DAQehRANCAAQhGuCqDer36ql2
vdKTLsYw81y7L/pPRCVNO0d/W2Bhdozwvo3Ia2BGZ8YZ29hccRFExzANAUZkLzx7
SS8SiQLl
-----END PRIVATE KEY-----